import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

file_path = 'house.csv'
df = pd.read_csv(file_path)

print(df.head())

plt.figure(figsize=(10, 6))
sns.histplot(df['Price'], kde=True, bins=30)
plt.title('Distribution of House Prices')
plt.xlabel('Price')
plt.ylabel('Frequency')
plt.show()

plt.figure(figsize=(12, 8))
correlation_matrix = df.corr()
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Heatmap')
plt.show()

avg_price_bedrooms = df.groupby('Num_Bedrooms')['Price'].mean()
plt.figure(figsize=(8, 5))
avg_price_bedrooms.plot(kind='bar', color='skyblue')
plt.title('Average Price by Number of Bedrooms')
plt.xlabel('Number of Bedrooms')
plt.ylabel('Average Price')
plt.xticks(rotation=0)
plt.show()

plt.figure(figsize=(10, 6))
sns.scatterplot(x='Square_Feet', y='Price', data=df, hue='Num_Bedrooms', palette='viridis', alpha=0.7)
plt.title('Price vs. Square Feet')
plt.xlabel('Square Feet')
plt.ylabel('Price')
plt.show()

plt.figure(figsize=(10, 6))
sns.boxplot(x='Num_Bathrooms', y='Price', data=df, palette='Set3')
plt.title('Prices by Number of Bathrooms')
plt.xlabel('Number of Bathrooms')
plt.ylabel('Price')
plt.show()

plt.figure(figsize=(10, 6))
sns.lineplot(x='Year_Built', y='Price', data=df, ci=None)
plt.title('Price Trends by Year Built')
plt.xlabel('Year Built')
plt.ylabel('Price')
plt.show()

garden_price = df.groupby('Has_Garden')['Price'].mean()
plt.figure(figsize=(8, 5))
garden_price.plot(kind='bar', color=['red', 'green'])
plt.title('Price Based on Garden Availability')
plt.xlabel('Has Garden')
plt.ylabel('Average Price')
plt.xticks(rotation=0)
plt.show()

plt.figure(figsize=(12, 6))
sns.boxplot(x='Garage_Size', y='Price', data=df, palette='coolwarm')
plt.title('Price by Garage Size')
plt.xlabel('Garage Size')
plt.ylabel('Price')
plt.show()

plt.figure(figsize=(10, 6))
sns.scatterplot(x='Distance_to_Center', y='Price', data=df, alpha=0.7, color='orange')
plt.title('Distance to Center vs. Price')
plt.xlabel('Distance to Center')
plt.ylabel('Price')
plt.show()

floors_price = df.groupby('Num_Floors')['Price'].mean()
plt.figure(figsize=(8, 5))
floors_price.plot(kind='bar', color='teal')
plt.title('Average Price by Number of Floors')
plt.xlabel('Number of Floors')
plt.ylabel('Average Price')
plt.xticks(rotation=0)
plt.show()

plt.figure(figsize=(12, 6))
sns.barplot(x='Location_Score', y='Price', data=df, palette='viridis')
plt.title('Average Price by Location Score')
plt.xlabel('Location Score')
plt.ylabel('Average Price')
plt.xticks(rotation=90)
plt.show()

plt.figure(figsize=(10, 6))
sns.histplot(df['Square_Feet'], kde=True, bins=30, color='purple')
plt.title('Distribution of Square Feet')
plt.xlabel('Square Feet')
plt.ylabel('Frequency')
plt.show()

pool_price = df.groupby('Has_Pool')['Price'].mean()
plt.figure(figsize=(8, 5))
pool_price.plot(kind='bar', color=['blue', 'orange'])
plt.title('Price Based on Pool Availability')
plt.xlabel('Has Pool')
plt.ylabel('Average Price')
plt.xticks(rotation=0)
plt.show()

plt.figure(figsize=(10, 6))
sns.scatterplot(x='Location_Score', y='Price', data=df, hue='Has_Garden', palette='coolwarm', alpha=0.7)
plt.title('Price vs. Location Score')
plt.xlabel('Location Score')
plt.ylabel('Price')
plt.show()

plt.figure(figsize=(12, 6))
sns.countplot(x='Year_Built', data=df, palette='coolwarm', order=df['Year_Built'].value_counts().index[:20])
plt.title('Count of Houses by Year Built')
plt.xlabel('Year Built')
plt.ylabel('Count')
plt.xticks(rotation=90)
plt.show()

print("Analysis Completed.")
